### ISSUE TITLE
角色获取权限时报错

### ISSUE THREAD

**Issue by capapchy** [xiaoliang1314/AbpVnextModule#1]
![捕获](https://user-images.githubusercontent.com/12610655/78513693-05171580-77e0-11ea-8b65-47fb89c95b96.PNG)

**Comment by capapchy** [comment]
public override async Task<PermissionValueProviderGrantInfo> CheckAsync(string name, string providerName, string providerKey)
        {
            if (providerName == Name)
            {
                return new PermissionValueProviderGrantInfo(
                    await PermissionGrantRepository.FindAsync(name, providerName, providerKey) != null,
                    providerKey
                );
            }
            if (providerName == RolePermissionValueProvider.ProviderName)
            {
                var roleId = Guid.Parse(providerKey);
                 //说明，providerKey不是guid类型，转换时发生异常
                var roleNames = await OrganizationUnitRoleFinder.GetRolesAsync(roleId);
                foreach (var roleName in roleNames)
                {
                    var permissionGrant = await PermissionGrantRepository.FindAsync(name, Name, roleName);
                    if (permissionGrant != null)
                    {
                        return new PermissionValueProviderGrantInfo(true, roleName);
                    }
                }
            }

**Comment by realmingliang** [comment]
已修复

**Comment by realmingliang** [comment]
拉取最新版即可
