### ISSUE TITLE
还原出问题。

### ISSUE THREAD

**Issue by CHENJKNB** [xiaoliang1314/AbpVnextModule#3]
为啥 我还原 老是出问题啊。
就是Host这个项目有问题 其他项目没问题
![image](https://user-images.githubusercontent.com/18523983/86984988-a7b9a880-c1c2-11ea-9d8a-974af890f70d.png)

**Comment by realmingliang** [comment]
host 项目下的npm包还原需要翻墙，可以删除package.json 试试
