### ISSUE TITLE
国际化这块还不行啊

### ISSUE THREAD

**Issue by laosandegudai** [xiaoliang1314/AbpVnextModule#4]
菜单的国际化我试了前端切换不了。

**Comment by laosandegudai** [comment]
看了下源码，使用itemrender实现了，不知道正确的该怎么搞。

**Comment by realmingliang** [comment]
需要关闭前端的国际化，然后从配置中根据key获取到国际化资源

**Comment by laosandegudai** [comment]
还在呢，看了好几次你没更，我就关闭了。多谢你的前端示例了。

**Comment by realmingliang** [comment]
工作太忙，你可以把前端的umi插件改造一下，但是vnext国际化资源来自不同的源（模块），可能需要处理下

**Comment by laosandegudai** [comment]
谢了老乡，我主要是后端，看你的前端移植的挺好的。
