### ISSUE TITLE
BasicLayout,breadcrumbRender, Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by mrs01dev** [xiaoliang1314/AbpVnextModule#5]
On react app , after login , an error page appear

![image](https://user-images.githubusercontent.com/64358630/117160625-1f6e4a80-ad76-11eb-97f8-31362f017176.png)

TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
_nonIterableSpread
./node_modules/.pnpm/@babel+runtime@7.12.5/node_modules/@babel/runtime/helpers/esm/nonIterableSpread.js:2
  1 | export default function _nonIterableSpread() {
> 2 |   throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
  3 | }
View compiled
_toConsumableArray
./node_modules/.pnpm/@babel+runtime@7.12.5/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js:6
  3 | import unsupportedIterableToArray from "@babel/runtime/helpers/esm/unsupportedIterableToArray";
  4 | import nonIterableSpread from "@babel/runtime/helpers/esm/nonIterableSpread";
  5 | export default function _toConsumableArray(arr) {
> 6 |   return arrayWithoutHoles(arr) || iterableToArray(arr) || unsupportedIterableToArray(arr) || nonIterableSpread();
  7 | }
View compiled
breadcrumbRender
./src/layouts/BasicLayout.tsx:162
  159 |   return <Link to={menuItemProps.path}>{defaultDom}</Link>;
  160 | }}
  161 | breadcrumbRender={(routers = []) => [
> 162 |   {
      | ^  163 |     path: '/',
  164 |     breadcrumbName: '首页',
  165 |   },

How to solve this issue ?

**Comment by realmingliang** [comment]
It should be the NPM package version that causes the problem

**Comment by realmingliang** [comment]
I have a new React template here    https://github.com/potatoabp/abp-vnext-react
